apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lviju3b9g-go 
  janus-idp.io/tekton: lviju3b9g-go
  backstage.io/kubernetes-id: lviju3b9g-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lviju3b9g-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  